// Contact Page - Exact pixel-perfect reproduction of Contact.html
export function contactPage(content: Record<string, Record<string, string>> = {}): string {
  const getContent = (section: string, key: string, fallback: string): string => {
    return content[section]?.[key] || fallback;
  };

  return `<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>fitup · Contact</title>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="/static/styles/contact.css">
</head>
<body>

  <!-- Top Navigation -->
  <nav class="top-nav" id="topNav">
    <div class="nav-left">
      <a href="/" class="nav-logo">
        <img src="https://i.ibb.co/VWs7tk3q/605997942-17850007239614033-1994629091166485047-n.jpg" alt="fitup" class="nav-logo-img">
        <span>© fitup</span>
      </a>
    </div>
    
    <div class="nav-center-left">
      <a href="/" class="nav-menu-item">Accueil</a>
    </div>
    
    <div class="nav-center">
      <div class="nav-stripe-cluster">
        ${Array(30).fill('<div class="stripe"></div>').join('')}
      </div>
    </div>
    
    <div class="nav-center-right">
      <div class="nav-lang-toggle">
        <span class="lang-active">Fr</span>
        <span class="lang-separator">/</span>
        <span class="lang-inactive">En</span>
      </div>
    </div>
    
    <div class="nav-right">
      <button class="nav-menu-btn">
        <span class="menu-text">Menu</span>
        <span class="menu-icon">
          <span class="menu-line menu-line-h"></span>
          <span class="menu-line menu-line-v"></span>
        </span>
      </button>
    </div>
  </nav>

  <!-- Main Content -->
  <main class="main-content">
    <h1 class="page-title" data-content="hero.title">${getContent('hero', 'title', 'Prenez rendez-vous')}</h1>
    <p class="page-subtitle" data-content="hero.subtitle">${getContent('hero', 'subtitle', 'Choisissez un créneau qui vous convient')}</p>

    <!-- Calendar Section -->
    <div class="calendar-section">
      <h2 class="section-title">Sélectionnez une date</h2>
      
      <!-- Month Navigation -->
      <div class="calendar-nav">
        <button class="cal-nav-btn" id="prevMonth">← Précédent</button>
        <span class="cal-month-label" id="monthLabel">Janvier 2026</span>
        <button class="cal-nav-btn" id="nextMonth">Suivant →</button>
      </div>
      
      <!-- Calendar Grid -->
      <div class="calendar-grid" id="calendarGrid">
        <!-- Days will be generated by JS -->
      </div>
      
      <!-- Time Slots -->
      <div class="time-slots-container" id="timeSlotsContainer" style="display: none;">
        <h3 class="time-slots-title">Créneaux disponibles</h3>
        <div class="time-slots" id="timeSlots">
          <!-- Slots generated by JS -->
        </div>
      </div>
    </div>

    <!-- Form Section (Hidden until slot selected) -->
    <div id="_builder-form" class="builder-form" style="display: none;">
      <h2 class="section-title">Vos informations</h2>
      <p class="selected-slot-info" id="selectedSlotInfo"></p>
      
      <form id="contactForm">
        <div class="form-row">
          <div class="form-group">
            <label for="prenom">Prénom *</label>
            <input type="text" id="prenom" name="prenom" placeholder="Votre prénom" required>
          </div>
          <div class="form-group">
            <label for="nom">Nom *</label>
            <input type="text" id="nom" name="nom" placeholder="Votre nom" required>
          </div>
        </div>
        
        <div class="form-row">
          <div class="form-group">
            <label for="telephone">Numéro de téléphone *</label>
            <input type="tel" id="telephone" name="telephone" placeholder="+212 6XX XXX XXX" required>
          </div>
          <div class="form-group">
            <label for="email">Email *</label>
            <input type="email" id="email" name="email" placeholder="votre@email.com" required>
          </div>
        </div>
        
        <div class="form-row">
          <div class="form-group">
            <label for="entreprise">Nom de l'entreprise</label>
            <input type="text" id="entreprise" name="entreprise" placeholder="Votre entreprise">
          </div>
          <div class="form-group">
            <label for="poste">Titre du poste</label>
            <input type="text" id="poste" name="poste" placeholder="Votre fonction">
          </div>
        </div>
        
        <div class="form-group full-width">
          <label for="budget">Budget estimé</label>
          <select id="budget" name="budget">
            <option value="">Sélectionner un budget...</option>
            <option value="5000-10000">5 000 - 10 000 MAD</option>
            <option value="10000-25000">10 000 - 25 000 MAD</option>
            <option value="25000-50000">25 000 - 50 000 MAD</option>
            <option value="50000+">50 000+ MAD</option>
          </select>
        </div>
        
        <div class="form-group full-width">
          <label for="message">Message</label>
          <textarea id="message" name="message" rows="4" placeholder="Décrivez votre projet ou vos besoins..."></textarea>
        </div>
        
        <button type="submit" class="submit-btn">Confirmer le rendez-vous</button>
      </form>
    </div>
    
    <!-- Success Message -->
    <div id="successMessage" class="success-message" style="display: none;">
      <div class="success-icon">✓</div>
      <h2>Rendez-vous confirmé!</h2>
      <p>Nous vous contacterons très bientôt.</p>
      <a href="/" class="back-home-btn">Retour à l'accueil</a>
    </div>
  </main>

  <script src="/static/js/contact.js"></script>
</body>
</html>`;
}
